name: Build Docker

"on":
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        php: ["8.5", "8.4"]
        node: [24, 22]
        include:
          - php: "8.5"
            node: 24
            latest: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Docker meta
        uses: docker/metadata-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            curicows/php-laravel
            ghcr.io/curicows/php-laravel
          labels: |
            org.opencontainers.image.vendor=Curicows


      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v4

      - name: Hub login
        uses: docker/login-action@v4
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Ghcr login
        uses: docker/login-action@v4
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base
        uses: docker/build-push-action@v7
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          provenance: false
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=${{matrix.php}}
            nodeVersion=${{matrix.node}}
          target: base
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            curicows/php-laravel:php-${{matrix.php}}
            ghcr.io/curicows/php-laravel:php-${{matrix.php}}
            ${{ matrix.latest == true && 'curicows/php-laravel:latest' || '' }}
            ${{ matrix.latest == true && 'ghcr.io/curicows/php-laravel:latest' || '' }}

      - name: Build Node
        uses: docker/build-push-action@v7
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          provenance: false
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=${{matrix.php}}
            nodeVersion=${{matrix.node}}
          target: node
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            curicows/php-laravel:php-${{matrix.php}}-node-${{matrix.node}}
            ghcr.io/curicows/php-laravel:php-${{matrix.php}}-node-${{matrix.node}}
            ${{ matrix.latest == true && 'curicows/php-laravel:node' || '' }}
            ${{ matrix.latest == true && 'ghcr.io/curicows/php-laravel:node' || '' }}

      - name: Build Chrome
        uses: docker/build-push-action@v7
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          provenance: false
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            phpVersion=${{matrix.php}}
            nodeVersion=${{matrix.node}}
          target: chrome
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            curicows/php-laravel:chrome-php-${{matrix.php}}-node-${{matrix.node}}
            ghcr.io/curicows/php-laravel:chrome-php-${{matrix.php}}-node-${{matrix.node}}
            ${{ matrix.latest == true && 'curicows/php-laravel:chrome' || '' }}
            ${{ matrix.latest == true && 'ghcr.io/curicows/php-laravel:chrome' || '' }}
